services:
  - type: web
    name: catalise
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd meu_projeto && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT meu_projeto.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.9"
