release: cd meu_projeto && python manage.py migrate --noinput
web: cd meu_projeto && python manage.py collectstatic --noinput && gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT meu_projeto.wsgi
