from django.urls import path

from . import views

urlpatterns = [
    path(
        "batelada/onemols",
        views.timebateladadirectonereagentView,
        name="time-batelada-direct-one-reagent",
    ),
    path(
        "batelada/one",
        views.timebateladadirectonereagentnovarmolsView,
        name="time-batelada-direct-one-reagent-no-var-mols",
    ),
    path(
        "batelada/two",
        views.timebateladadirecttworeagentnovarmolsView,
        name="time-batelada-direct-two-reagent-no-var-mols",
    ),
    path(
        "batelada/twomols",
        views.timebateladadirecttworeagentView,
        name="time-batelada-direct-two-reagent",
    ),
    path(
        "cstr/onemols",
        views.calculatecstrvolumedirectonereagentView,
        name="calculate-cstr-volume-direct-one-reagent",
    ),
    path(
        "cstr/one",
        views.calculatecstrvolumedirectonereagentnovarmolsView,
        name="calculate-csrt-volume-direct-one-reagent-no-var-mols",
    ),
    path(
        "cstr/two",
        views.calculatecstrvolumedirecttworeagentnovarmolsView,
        name="calculate-cstr-volume-direct-two-reagent-no-var-mols",
    ),
    path(
        "cstr/twomols",
        views.calculatecstrvolumedirecttworeagentView,
        name="calculate-cstr-volume-direct-two-reagent",
    ),
    path(
        "pfr/onemols",
        views.calculatepfrvolumedirectonereagentView,
        name="calculate-pfr-volume-direct-one-reagent",
    ),
    path(
        "pfr/one",
        views.calculatepfrvolumedirectonereagentnovarmolsView,
        name="calculate-pfr-volume-direct-one-reagent-no-var-mols",
    ),
    path(
        "pfr/two",
        views.calculatepfrvolumedirecttworeagentnovarmolsView,
        name="calculate-pfr-volume-direct-two-reagent-no-var-mols",
    ),
    path(
        "pfr/twomols",
        views.calculatepfrvolumedirecttworeagentView,
        name="calculate-pfr-volume-direct-two-reagent",
    ),
    path(
        "semibatelada/concentration",
        views.calculate_semibatelada_concentrationView,
        name="calculate-semibatelada-concentration",
    ),
    path(
        "semibatelada/startuptime",
        views.calculate_startup_timeView,
        name="calculate-startup-time",
    ),
    path(
        "semibatelada/startupconcentration",
        views.calculate_startup_concentrationView,
        name="calculate-startup-concentration",
    ),
    path(
        "semibatelada/quedapressaotypeone",
        views.calculate_quedapressao_typeone_massadecatalisadorView,
        name="calculate-quedapressao-typeone-massadecatalisador",
    ),
    path(
        "semibatelada/quedapressaotypetwo",
        views.calculate_quedapressao_typetwo_massadecatalisadorView,
        name="calculate-quedapressao-typetwo-massadecatalisador",
    ),
    path(
        "semibatelada/quedapressaotypeonecomprimento",
        views.calculate_quedapressao_typeone_comprimentoView,
        name="calculate-quedapressao-typeone-comprimento",
    ),
    path(
        "semibatelada/quedapressaotypetwocomprimento",
        views.calculate_quedapressao_typetwo_comprimentoView,
        name="calculate-quedapressao-typetwo-comprimento",
    ),
    path(
        "semibatelada/quedapressaoreatortubular",
        views.calculate_quedapressao_reatortubularView,
        name="calculate-quedapressao-reatortubular",
    ),
    path(
        "semibatelada/calculatetempbatelada",
        views.calculate_temp_bateladaView,
        name="calculate-temp-batelada",
    ),
    path(
        "semibatelada/calculatetempcstrordemum",
        views.calculate_temp_cstr_ordem_umView,
        name="calculate-temp-cstr-ordem-um",
    ),
    path(
        "semibatelada/calculatetempcstrordemdois",
        views.calculate_temp_cstr_ordem_doisView,
        name="calculate-temp-cstr-ordem-dois",
    ),
    path(
        "semibatelada/calculatetempcstrordemumdoisreagentes",
        views.calculate_temp_cstr_ordem_um_doisreagentesView,
        name="calculate-temp-cstr-ordem-um-doisreagentes",
    ),
    path(
        "semibatelada/calculatetemppfrordemum",
        views.calculate_temp_pfr_ordem_umView,
        name="calculate-temp-pfr-ordem-um",
    ),
    path(
        "semibatelada/calculatetemppfrordemdois",
        views.calculate_temp_pfr_ordem_doisView,
        name="calculate-temp-pfr-ordem-dois",
    ),
    path(
        "semibatelada/calculatetemppfrordemumdoisreagentes",
        views.calculate_temp_pfr_ordem_um_doisreagentesView,
        name="calculate-temp-pfr-ordem-um-doisreagentes",
    ),
    path(
        "semibatelada/calculatetemppfrordemumreversivel",
        views.calculate_temp_pfr_ordem_um_reversivelView,
        name="calculate-temp-pfr-ordem-um-reversivel",
    ),
    path(
        "semibatelada/calculatetempcstrordemumreversivel",
        views.calculate_temp_cstr_ordem_um_reversivelView,
        name="calculate-temp-cstr-ordem-um-reversivel",
    ),
]
